dist: trusty
sudo: false
language: c

compiler:
  -  gcc

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - python3
      env:
        - MATRIX_EVAL="CC=gcc-7"

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - make && make test
